// GENERATED by tools/merge-export.mjs — do not hand-edit.
// Builder-authored quests (ClearLessons Press · Crystal Quest module).
// Loaded after content.js: same titles override, new titles join their land.
const QUEST_PACKS = /*__PACKS_START__*/{}/*__PACKS_END__*/;
for (const [title, q] of Object.entries(QUEST_PACKS)) {
  QUEST_CONTENT[title] = q;
  const land = typeof LANDS !== 'undefined' && LANDS[q.land];
  if (land && Array.isArray(land.quests) && !land.quests.some(x => x.name === title)) {
    land.quests.push({ name: title, icon: q.icon || '✦' });
  }
}
