#!/usr/bin/env node
// merge-export.mjs — merge a ClearLessons Press export into the game.
//
//   node tools/merge-export.mjs <export.json>     merge/update quests from a package
//   node tools/merge-export.mjs --init            write an empty pack file
//
// This NEVER edits js/content.js. Builder-authored quests live in the generated
// js/content-packs.js, loaded after content.js: same-title quests override the
// hand-written ones, new titles are appended to their land's quest list. Running
// the tool again with a newer export updates in place (merge by quest title).
// This is the "merge" half of export-for-review: a human reviews the export,
// runs this, plays it locally, then commits.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PACK_PATH = join(ROOT, 'js', 'content-packs.js');
const START = '/*__PACKS_START__*/', END = '/*__PACKS_END__*/';

function currentPacks() {
  if (!existsSync(PACK_PATH)) return {};
  const src = readFileSync(PACK_PATH, 'utf8');
  const a = src.indexOf(START), b = src.indexOf(END);
  if (a < 0 || b < 0) return {};
  try { return JSON.parse(src.slice(a + START.length, b)); } catch { return {}; }
}

function writePacks(packs) {
  const body = `// GENERATED by tools/merge-export.mjs — do not hand-edit.
// Builder-authored quests (ClearLessons Press · Crystal Quest module).
// Loaded after content.js: same titles override, new titles join their land.
const QUEST_PACKS = ${START}${JSON.stringify(packs, null, 2)}${END};
for (const [title, q] of Object.entries(QUEST_PACKS)) {
  QUEST_CONTENT[title] = q;
  const land = typeof LANDS !== 'undefined' && LANDS[q.land];
  if (land && Array.isArray(land.quests) && !land.quests.some(x => x.name === title)) {
    land.quests.push({ name: title, icon: q.icon || '✦' });
  }
}
`;
  writeFileSync(PACK_PATH, body);
}

const arg = process.argv[2];
if (!arg) { console.error('Usage: node tools/merge-export.mjs <export.json> | --init'); process.exit(1); }

if (arg === '--init') {
  writePacks({});
  console.log('Wrote empty pack file:', PACK_PATH);
  process.exit(0);
}

const pkg = JSON.parse(readFileSync(arg, 'utf8'));
if (!pkg.quests || typeof pkg.quests !== 'object') { console.error('Not a Press export: no "quests" key.'); process.exit(1); }

// "It rendered" is not validation: a hand-edited or corrupted package can be
// structurally wrong yet draw a clean-looking broken quest. Refuse it here,
// by name, before it ever reaches a student.
function checkItem(where, it) {
  const fail = (why) => { throw new Error(`${where}: ${why}`); };
  if (!it || typeof it.q !== 'string' || !it.q.trim()) fail('missing stem (q)');
  const type = it.type || 'multiple_choice';
  if (type === 'multiple_choice') {
    if (!Array.isArray(it.a) || it.a.length < 2) fail('multiple choice needs an options array');
    for (const o of it.a) {
      const ok = typeof o === 'string' ? o.length > 0 : (o && (o.text || o.svg));
      if (!ok) fail('an option has neither text nor a figure');
    }
    if (typeof it.c !== 'number' || it.c < 0 || it.c >= it.a.length) fail('correct index c out of range');
  }
  if (it.figure && !it.figure.svg) fail('figure present but has no svg'); else if (type === 'drag_drop') {
    if (!Array.isArray(it.zones) || it.zones.length < 2) fail('drag_drop needs ≥2 zones');
    if (!Array.isArray(it.tokens) || it.tokens.length < 2) fail('drag_drop needs ≥2 tokens');
    if (!it.answer || typeof it.answer !== 'object') fail('drag_drop missing answer map');
    const placed = Object.values(it.answer).flat();
    for (const t of it.tokens) if (!placed.includes(t.id)) fail(`token "${t.text}" is in no zone's answer`);
  } else if (type === 'multiselect') {
    if (!Array.isArray(it.a) || it.a.length < 3) fail('multiselect needs ≥3 options');
    if (!Array.isArray(it.cs) || !it.cs.length || it.cs.some((k) => k < 0 || k >= it.a.length)) fail('multiselect cs invalid');
  } else if (type === 'dropdown') {
    const ids = Object.keys(it.blanks || {});
    if (!ids.length) fail('dropdown has no blanks');
    for (const b of ids) {
      if (!(it.blanks[b].opts || []).length) fail(`blank [${b}] has no options`);
      if (!it.q.includes(`[${b}]`)) fail(`stem never uses [${b}]`);
    }
  } else if (type === 'equation_entry') {
    if (!Array.isArray(it.accept) || !it.accept.length) fail('equation_entry has an empty accept list');
  } else if (type === 'graph_plot') {
    if (it.kind && it.kind !== 'bars') fail(`graph_plot kind "${it.kind}" not supported by the game yet (only 'bars')`);
    if (!Array.isArray(it.categories) || it.categories.length < 2) fail('graph_plot needs ≥2 categories');
    const max = it.max || 10;
    for (const c of it.categories) {
      if (!c.label) fail('a graph category is missing its label');
      if (typeof c.target !== 'number' || c.target < 0 || c.target > max) fail(`category "${c.label}" target out of 0..${max}`);
    }
  } else fail(`unknown item type "${type}" — the game cannot render it`);
}
for (const [title, q] of Object.entries(pkg.quests)) {
  try {
    ['pre', 'practice', 'post'].forEach((step) => (q[step] || []).forEach((it, i) => checkItem(`"${title}" ${step}[${i + 1}]`, it)));
    (q.game?.problems || []).forEach((p, i) => {
      if (!p.q || p.c === undefined || !Array.isArray(p.opts)) throw new Error(`"${title}" game[${i + 1}]: needs q, c, opts`);
    });
  } catch (e) { console.error('REFUSED — ' + e.message); process.exit(1); }
}

const packs = currentPacks();
const before = Object.keys(packs).length;
for (const [title, q] of Object.entries(pkg.quests)) {
  if (q.lessonRef && !q.lesson) {
    console.warn(`⚠ "${title}" references Independent Lesson ${q.lessonRef.external_id} (${q.lessonRef.status}) — the game cannot embed lessons yet; it will show an empty Lesson step unless a fallback is added.`);
  }
  packs[title] = q;
}
writePacks(packs);
console.log(`Merged ${Object.keys(pkg.quests).length} quest(s) from ${arg} (pack now holds ${Object.keys(packs).length}, was ${before}).`);
console.log('Review locally, bump the ?v= on script tags if deploying, then commit js/content-packs.js.');
