#!/usr/bin/env node
// merge-export.mjs — merge a ClearLessons Press export into the game.
//
//   node tools/merge-export.mjs <export.json>     merge/update quests from a package
//   node tools/merge-export.mjs --init            write an empty pack file
//
// This NEVER edits js/content.js. Builder-authored quests live in the generated
// js/content-packs.js, loaded after content.js: same-title quests override the
// hand-written ones, new titles are appended to their land's quest list. Running
// the tool again with a newer export updates in place (merge by quest title).
// This is the "merge" half of export-for-review: a human reviews the export,
// runs this, plays it locally, then commits.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PACK_PATH = join(ROOT, 'js', 'content-packs.js');
const START = '/*__PACKS_START__*/', END = '/*__PACKS_END__*/';

function currentPacks() {
  if (!existsSync(PACK_PATH)) return {};
  const src = readFileSync(PACK_PATH, 'utf8');
  const a = src.indexOf(START), b = src.indexOf(END);
  if (a < 0 || b < 0) return {};
  try { return JSON.parse(src.slice(a + START.length, b)); } catch { return {}; }
}

function writePacks(packs) {
  const body = `// GENERATED by tools/merge-export.mjs — do not hand-edit.
// Builder-authored quests (ClearLessons Press · Crystal Quest module).
// Loaded after content.js: same titles override, new titles join their land.
const QUEST_PACKS = ${START}${JSON.stringify(packs, null, 2)}${END};
for (const [title, q] of Object.entries(QUEST_PACKS)) {
  QUEST_CONTENT[title] = q;
  const land = typeof LANDS !== 'undefined' && LANDS[q.land];
  if (land && Array.isArray(land.quests) && !land.quests.some(x => x.name === title)) {
    land.quests.push({ name: title, icon: q.icon || '✦' });
  }
}
`;
  writeFileSync(PACK_PATH, body);
}

const arg = process.argv[2];
if (!arg) { console.error('Usage: node tools/merge-export.mjs <export.json> | --init'); process.exit(1); }

if (arg === '--init') {
  writePacks({});
  console.log('Wrote empty pack file:', PACK_PATH);
  process.exit(0);
}

const pkg = JSON.parse(readFileSync(arg, 'utf8'));
if (!pkg.quests || typeof pkg.quests !== 'object') { console.error('Not a Press export: no "quests" key.'); process.exit(1); }

const packs = currentPacks();
const before = Object.keys(packs).length;
for (const [title, q] of Object.entries(pkg.quests)) {
  if (q.lessonRef && !q.lesson) {
    console.warn(`⚠ "${title}" references Independent Lesson ${q.lessonRef.external_id} (${q.lessonRef.status}) — the game cannot embed lessons yet; it will show an empty Lesson step unless a fallback is added.`);
  }
  packs[title] = q;
}
writePacks(packs);
console.log(`Merged ${Object.keys(pkg.quests).length} quest(s) from ${arg} (pack now holds ${Object.keys(packs).length}, was ${before}).`);
console.log('Review locally, bump the ?v= on script tags if deploying, then commit js/content-packs.js.');
